[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.35"
evm_version = "osaka"

fs_permissions = [{ access = "read-write", path = "./script/deployments" }]

[fmt]
ignore = ["lib/**/*.sol", "src/lib/**/*.sol"]

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
bsc-testnet = "https://bsc-testnet-rpc.publicnode.com"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56, url = "https://api.etherscan.io/v2/api?chainid=56" }
bsc-testnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api.etherscan.io/v2/api?chainid=97" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
